FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./

COPY client/package*.json clinet/
RUN npm install-clinet --only=production

COPY client/package*.json server/
RUN npm install-server --only=production

COPY client/ client/
RUN npm run build --prefix client

COPY server/ server/

USER node

CMD ["npm", "start","--prefix","server"]

EXPOSE 8000